image: alpine

tags:
  - gitci2

before_script:
  - apk --no-cache add cmake make g++

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./bin/test_Spike
