image: alpine

before_script:
  - apk update
  - apk add --update cmake make g++ lcov

stages:
  - build
  - test
  - coverage

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - make Spike_coverage
  artifacts:
    paths:
      - build/Spike_coverage.info.cleaned
      - bin/test_Spike
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./bin/test_Spike

coverage:
  stage: coverage
  script:
    - cd build
    - lcov --list Spike_coverage.info.cleaned
