image: debian:stable

before_script:
   - apt-get update  
   - apt-get -y install cmake make g++ libboost-all-dev libfftw3-dev liblapack-dev libgsl-dev
  
stages:
  - build

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour