image: alpine

before_script:
  - apk --no-cache add cmake make g++

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - "*.o"

test:
  stage: test
  script:
    - ./bin/test_Spike
