image: alpine

before_script:
  - apk --no-cache add cmake make g++

cache:
  paths:
    - "*/*/*/*.o"
    - "*/*/*/*/*.o"
    - "*/*/*/*/*/*.o"
    - "*/*/*/*/*/*/*.o"

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./bin/test_Spike
