image: alpine

before_script:
  - apk update
  - apk add --update cmake make g++ boost-dev

stages:
  - build
  - test

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./bin/test_Spike
