image: alpine

before_script:
  - echo http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
  - echo http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
  - echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
  - apk update
  - apk add --update cmake make g++ lcov

stages:
  - build
  - test
  - coverage

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/

build: 
  stage: build
  script: 
    - mkdir -p build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - bin/test_Spike
      - lib/
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./bin/test_Spike

coverage:
  stage: coverage
  script:
    - make Spike_coverage
    - lcov --list Spike_coverage.info.cleaned
